### ISSUE TITLE
Problems arising from the direct shutdown of the network

### ISSUE THREAD

**Issue by iwctwbai** [miguelgrinberg/python-socketio#274]
Hi！
I shut down the network directly on a normal connection and the connection timed out and could not be reconnected.
How can I set the timeout manually and automatically reconnect when the connection fails?

# My Code: 
```
import socketio
import time

id_socket = socketio.Client(reconnection=True,
                            reconnection_attempts = float('Inf'),
                            reconnection_delay=1,
                            reconnection_delay_max = 1,
                            randomization_factor = 0,
                            logger = True,
                            engineio_logger=True)

@id_socket.on('connect')
def on_connect():
    print('connected!!!')

@id_socket.on('disconnect')
def on_disconnect():
    print('disconnect!!!')

def do_something():
    print("working")

if __name__ == "__main__":
    id_socket.connect(url='localhost:1288')
    while True:
        time.sleep(1)
        do_something()
```

# My Log:
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': '8aqxvbrh9823d89415169812', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
Attempting WebSocket upgrade to ws://localhost:1288/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet MESSAGE data 0
Namespace / is connected
connected!!!
Received packet PONG data None
working
working
working
working
working
working
working
working

__________________________________________HINT_____________________________________________
Close network connection! 
Close network connection!
Close network connection!
Close network connection!
Close network connection!
__________________________________________HINT_____________________________________________

working
working
working
working
working
Sending packet PING data None
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
PONG response has not been received, aborting
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Unexpected error "[Errno 60] Operation timed out", aborting
Waiting for write loop task to end
Exiting write loop task
Waiting for ping loop task to end
Exiting ping task
Engine.IO connection dropped
Connection failed, new attempt in 1.00 seconds
Exiting read loop task
disconnect!!!
working
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 320, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 439, in _handle_reconnect
    socketio_path=self.socketio_path)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 208, in connect
    engineio_path=socketio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 166, in connect
    url, headers, engineio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 267, in _connect_polling
    'GET', self.base_url + self._get_url_timestamp(), headers=headers)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 433, in _send_request
    return self.http.request(method, url, headers=headers, data=body)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working

__________________________________________HINT_____________________________________________
Recovery network！
Recovery network！
Recovery network！
Recovery network！
Recovery network！
Recovery network！
Recovery network！
__________________________________________HINT_____________________________________________

working
working
working
...（forever）

__________________________________________HINT_____________________________________________
Can't connect automatically
Can't connect automatically
Can't connect automatically
Can't connect automatically
Can't connect automatically
__________________________________________HINT_____________________________________________

### thanks!

**Comment by miguelgrinberg** [comment]
@iwctwbai could you please install the master branch of the python-engineio package and let me know if the problem is now fixed? Use this command:

    pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip

**Comment by iwctwbai** [comment]
I see. Should I change the code?

**Comment by miguelgrinberg** [comment]
No, just install the fixed code with the command I showed above and try again. If that works well, I'll do a release with the fix.

**Comment by iwctwbai** [comment]
thanks

I executed the order and got the results
```
Collecting https://github.com/miguelgrinberg/python-engineio/archive/master.zip
  Downloading https://github.com/miguelgrinberg/python-engineio/archive/master.zip
     | 522kB 856kB/s
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/site-packages (from python-engineio==3.5.0) (1.11.0)
Building wheels for collected packages: python-engineio
  Building wheel for python-engineio (setup.py) ... done
  Stored in directory: /private/var/folders/1x/4zy586kd373_7y89l1x2vp_r0000gn/T/pip-ephem-wheel-cache-rr6q89yx/wheels/82/00/f2/9f9a71f1038903372600084ccb8e37a1e61c6f5823bd37630c
Successfully built python-engineio
Installing collected packages: python-engineio
  Found existing installation: python-engineio 3.4.3
    Uninstalling python-engineio-3.4.3:
      Successfully uninstalled python-engineio-3.4.3
Successfully installed python-engineio-3.5.0
```

The problem still exists, just like before.
I didn't restart the computer or change the code.

**Comment by miguelgrinberg** [comment]
Can you show me the output of the application again please?

**Comment by iwctwbai** [comment]
Okay, wait a minute.

**Comment by iwctwbai** [comment]
# My Log
```
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'bebc54008823d74102c45597', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
Attempting WebSocket upgrade to ws://localhost:1288/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet MESSAGE data 0
Namespace / is connected
connected!!!
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Sending packet PING data None
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
PONG response has not been received, aborting
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
disconnect！！！
Unexpected error "[Errno 60] Operation timed out", aborting
Waiting for write loop task to end
Exiting write loop task
Waiting for ping loop task to end
Exiting ping task
Engine.IO connection dropped
Connection failed, new attempt in 1.00 seconds
Exiting read loop task
working
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 320, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 442, in _send_request
    return self.http.request(method, url, headers=headers, data=body)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 439, in _handle_reconnect
    socketio_path=self.socketio_path)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 208, in connect
    engineio_path=socketio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 166, in connect
    url, headers, engineio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 267, in _connect_polling
    'GET', self.base_url + self._get_url_timestamp(), headers=headers)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 443, in _send_request
    except requests.exceptions.RequestError:
AttributeError: module 'requests.exceptions' has no attribute 'RequestError'

working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
```

**Comment by iwctwbai** [comment]
Finally, I've restored my network connection, but it can't be reconnected.
output only "working" forever

**Comment by miguelgrinberg** [comment]
Thanks. Run the `pip install` command one more time and try again. If you still get errors, please send me another log.

**Comment by iwctwbai** [comment]
Thanks！
### Fix command
```
acpk001:~ acp$ python3 -m pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip
Collecting https://github.com/miguelgrinberg/python-engineio/archive/master.zip
  Downloading https://github.com/miguelgrinberg/python-engineio/archive/master.zip
     | 727kB 4.4MB/s
Requirement already satisfied (use --upgrade to upgrade): python-engineio==3.5.0 from https://github.com/miguelgrinberg/python-engineio/archive/master.zip in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/site-packages (from python-engineio==3.5.0) (1.11.0)
Building wheels for collected packages: python-engineio
  Building wheel for python-engineio (setup.py) ... done
  Stored in directory: /private/var/folders/1x/4zy586kd373_7y89l1x2vp_r0000gn/T/pip-ephem-wheel-cache-gjzm5xj0/wheels/82/00/f2/9f9a71f1038903372600084ccb8e37a1e61c6f5823bd37630c
Successfully built python-engineio
```

### My log
```
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'e84bd45b8923d74102705d1a', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
Attempting WebSocket upgrade to ws://localhost:1288/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet MESSAGE data 0
connected!!!
Namespace / is connected
Received packet PONG data None
working
working
__________________________________________________Tips：Disconnect network connection
__________________________________________________Tips：Disconnect network connection
__________________________________________________Tips：Disconnect network connection
__________________________________________________Tips：Disconnect network connection
__________________________________________________Tips：Disconnect network connection
working
working
working
working
Sending packet PING data None
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
PONG response has not been received, aborting
working
working
disconnect！！！
Unexpected error "[Errno 60] Operation timed out", aborting
Waiting for write loop task to end
Exiting write loop task
Waiting for ping loop task to end
Exiting ping task
Engine.IO connection dropped
Connection failed, new attempt in 1.00 seconds
Exiting read loop task
working
Attempting polling connection to http://localhost:1288/socket.io/?transport=polling&EIO=3
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
__________________________________________________Tips：Restore network connection
__________________________________________________Tips：Restore network connection
__________________________________________________Tips：Restore network connection
__________________________________________________Tips：Restore network connection
__________________________________________________Tips：Restore network connection
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 320, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 442, in _send_request
    return self.http.request(method, url, headers=headers, data=body)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=1288): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 439, in _handle_reconnect
    socketio_path=self.socketio_path)
  File "/usr/local/lib/python3.6/site-packages/socketio/client.py", line 208, in connect
    engineio_path=socketio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 166, in connect
    url, headers, engineio_path)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 267, in _connect_polling
    'GET', self.base_url + self._get_url_timestamp(), headers=headers)
  File "/usr/local/lib/python3.6/site-packages/engineio/client.py", line 443, in _send_request
    except requests.exceptions.RequestError:
AttributeError: module 'requests.exceptions' has no attribute 'RequestError'

working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
```

**Comment by miguelgrinberg** [comment]
For some reason the last code change that I've made did not get installed for you. Try the following:

```
pip uninstall python-engineio
pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip
```

**Comment by iwctwbai** [comment]
Thank you very much.
Let me have a try.

**Comment by iwctwbai** [comment]
It seems to have succeeded!
The disconnected function will be called back in a minute
A minute after networking calls back the reconnected function
How can I change the timeout here?

**Comment by iwctwbai** [comment]
It seems to be this "ping Timeout" parameter

**Comment by iwctwbai** [comment]
Sorry, it's my operation problem.
Bugs have been resolved.
Can you tell me when you release the fix version please?
I'll install it on the production machine.

**Comment by iwctwbai** [comment]
it's happend errors on the production machine
### My Log
```
Attempting polling connection to http://localhost:1276/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000, 'sid': 'a8a739049023d74100dd1c68'}
Engine.IO connection established
Attempting WebSocket upgrade to ws://localhost:1276/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet MESSAGE data 0
Namespace / is connected
working
working
working
working
working
working
working
working
working
working
working
working
Sending packet PING data None
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
PONG response has not been received, aborting
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
packet queue is empty, aborting
Exiting write loop task
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
Unexpected error "[Errno 104] Connection reset by peer", aborting
Waiting for write loop task to end
Waiting for ping loop task to end
Exiting ping task
Exiting read loop task
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
working
```

**Comment by eshao731** [comment]
I had the same problem！ My python-engineio is 3.5.0 . I want to know how to solve this problem. Throws a timeout exception without triggering a reconnection.Can I detect if my current connection is active? Or how do I catch this exception?


I'm disconnect!
Engine.IO connection dropped
Connection failed, new attempt in 1.36 seconds
2019-05-13 23:20:43.867085 [2333220, 2333225, 2333226]
Emitting event "readyForScores" [/]
Exception in thread Thread-705:
Traceback (most recent call last):
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/urllib3/connectionpool.py", line 317, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cf2-scorebot.hltv.org', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/socketio/client.py", line 439, in _handle_reconnect
    socketio_path=self.socketio_path)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/socketio/client.py", line 208, in connect
    engineio_path=socketio_path)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/engineio/client.py", line 166, in connect
    url, headers, engineio_path)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/engineio/client.py", line 267, in _connect_polling
    'GET', self.base_url + self._get_url_timestamp(), headers=headers)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/engineio/client.py", line 442, in _send_request
    return self.http.request(method, url, headers=headers, data=body)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/eshao/.virtualenvs/u9fun_crawler/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cf2-scorebot.hltv.org', port=443): Read timed out. (read timeout=None)

2019-05-13 23:21:43.881616 [2333220, 2333225, 2333226]
Emitting event "readyForScores" [/]

**Comment by miguelgrinberg** [comment]
The 3.5.0 release of python-engineio is older than this fix. Try 3.5.1.
